# Generated by Django 5.1.4 on 2024-12-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='libros',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='editorial',
            name='escritor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='artista',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
